"""Add Customer model and customer_id FK

Revision ID: 2daac307fae3
Revises: 
Create Date: 2026-04-02 21:03:50.889590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2daac307fae3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_service_records_customer_id', 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_service_records_customer_id', type_='foreignkey')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
